#!/usr/bin/env bash

function usage () {
    cat <<EOUSAGE
$(basename $0) [--kdir kernel-dir] [--dconf deconfig]
    --kdir: Kernel Source Address
    --dconf: defconfig to use
    --kout: Kernel build output
    --help: Show this help
EOUSAGE
    exit 0
}

extra_args=

kernel_dir=$(realpath "${HOME}/work/src/linux")
dconfig="defconfig"
kernel_out="~/work/tmp/linux-out"

aparse() {
    while [[ $# > 0 ]] ; do
        case "$1" in
            --kdir)
                kernel_dir=$2
                shift 2
                echo "Using kernel at ${kernel_dir}"
                ;;
            --dconf)
                dconfig=$2
                shift 2
                ;;
            --kout)
                kernel_out=$2
                if [ ! -e $2 ]; then
                    mkdir -p $2
                fi
                shift 2
                ;;
            --help)
                usage
                shift
                ;;
            *)
                extra_args="$extra_args $1"
                shift
                ;;
        esac
    done
}

aparse "$@"

echo extra args: $extra_args
echo ${dconfig}

#
# Auto probe toolchains
#
export ARCH=arm64

cross_toolchains=(
    aarch64-none-elf-
    aarch64-unknown-linux-gnu-
)

for cross_toolchain in ${cross_toolchains[@]}
do
    which ${cross_toolchain}gcc 1>/dev/null 2>&1
    if [ $? == 0 ]; then
        echo "Found ${cross_toolchain}"
        export CROSS_COMPILE=${cross_toolchain}
        break
    fi
done

if [ -z $CROSS_COMPILE ]; then
    echo "Can't found a valid toolchains"
    exit -1
fi


pushd $kernel_dir

# use clang
export LLVM=1

if [ x"$extra_args" != x ]; then
    lkmake O=${kernel_out} $extra_args -j8
    exit $?
fi

eval kernel_out=$kernel_out
export OUT_BUILD_KERNEL_DIR=$kernel_out
export SRC_KERNEL_DIR=$kernel_dir
export KCFLAGS="-Wno-int-conversion -Wno-incompatible-pointer-types-discards-qualifiers"

# Remove outdated kernel module
rm -rif ${kernel_out}/_install

#ROOTFS=~/work/src/rootfs/rootfs.cpio.gz
ROOTFS=~/work/images/initramfs.cpio
# ~/work/src/rootfs/rootfs.cpio.gz
 mkdir -p ${kernel_out}/_install
 lkmake O=${kernel_out} ${dconfig}

 echo "apply my enabled configs"
 ENABLE_CONFIGS=(
     CONFIG_GDB_SCRIPTS
     CONFIG_DYNAMIC_DEBUG_CORE
     CONFIG_DYNAMIC_DEBUG
     CONFIG_FW_LOADER_DEBUG
     CONFIG_TEST_DYNAMIC_DEBUG
     CONFIG_DEBUG_IRQFLAGS
     CONFIG_VIRTIO_MMIO
     CONFIG_VIRTIO_NET
     CONFIG_BLK_DEV_INITRD
     CONFIG_RD_GZIP
     CONFIG_GENERIC_PTDUMP
     CONFIG_PTDUMP_CORE
     CONFIG_PTDUMP_DEBUGFS
 )

 for config in ${ENABLE_CONFIGS[@]}; do
     echo "enable config: ${config}"
     ${kernel_out}/source/scripts/config --file ${kernel_out}/.config -e $config
 done

 echo "apply my disabled configs"
 DISABLE_CONFIGS=(
     CONFIG_MODULE_SIG
     CONFIG_MODVERSIONS
 )
 for config in ${DISABLE_CONFIGS[@]}; do
     echo "disable config: ${config}"
     ${kernel_out}/source/scripts/config --file ${kernel_out}/.config -d $config
 done

 lkmake O=${kernel_out} -j8
 lkmake O=${kernel_out} modules_install INSTALL_MOD_PATH=${kernel_out}/_install 2>/dev/null

     #LINUX_VER=$(cat ${kernel_out}/include/config/kernel.release)
     #depmod -b ${kernel_out}/_install/lib/modules/${LINUX_VER} -F ${kernel_out}/System.map ${LINUX_VER}

    if [ -e ~/work/src/code_snippet/kernel_moduless/ ]; then
        export KERNELDIR=${kernel_out}
        export ROOT_DIR=~/work/src/code_snippet/
        pushd ~/work/src/code_snippet/kernel_module/
        lkmake -j8
        find . -name "*.ko" -exec ${KERNELDIR}/scripts/sign-file sha512 ${KERNELDIR}/certs/signing_key.pem ${KERNELDIR}/certs/signing_key.x509 {} \;
        popd
    fi
#    ~/work/sync.sh
popd
